/*
 * httprr.trys.cc
 *
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 inherelab/httprr</code>
 *
 * API version: 0.0.1
 * Contact: in.798@qq.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"github.com/gookit/rux"
	"github.com/inherelab/httprr/app"
)

type Redirect struct {}

func AbsoluteRedirectNGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func RedirectNGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func RedirectToDelete(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func RedirectToGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func RedirectToPatch(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func RedirectToPost(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func RedirectToPut(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func RelativeRedirectNGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}
