/*
 * httprr.trys.cc
 *
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 inherelab/httprr</code>
 *
 * API version: 0.0.1
 * Contact: in.798@qq.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"github.com/gookit/rux"
	"github.com/inherelab/httprr/app"
)

func BrotliGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func DeflateGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func DenyGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func EncodingUtf8Get(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func GzipGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func HtmlGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func JsonGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func RobotsTxtGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func XmlGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}
