/*
 * httprr.trys.cc
 *
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 inherelab/httprr</code>
 *
 * API version: 0.0.1
 * Contact: in.798@qq.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"github.com/gookit/rux"
	"github.com/inherelab/httprr/app"
)

// Cookies APIs examples
type Cookies struct {}

func (grp *Cookies) AddRoutes(r *rux.Router) {
	r.GET("", grp.Get)
	r.GET("set", grp.Set)
	r.GET("delete", grp.Delete)
	r.GET("set/{name}/{value}", grp.SetNameValue)
}

func (*Cookies) Delete(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Cookies) Get(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Cookies) Set(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Cookies) SetNameValue(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}
