/*
 * httprr.trys.cc
 *
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 inherelab/httprr</code>
 *
 * API version: 0.0.1
 * Contact: in.798@qq.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"github.com/gookit/rux"
	"github.com/inherelab/httprr/app"
)

type Anything struct {}

func (grp *Anything) AddRoutes(r *rux.Router) {
	r.GET("", grp.Get)
	r.POST("", grp.Post)
	r.PUT("", grp.Put)
	r.PATCH("", grp.Patch)
	r.DELETE("", grp.Delete)

	r.GET("{anything}", grp.AnythingGet)
	r.POST("{anything}", grp.AnythingPost)
	r.PUT("{anything}", grp.AnythingPut)
	r.PATCH("{anything}", grp.AnythingPatch)
	r.DELETE("{anything}", grp.AnythingDelete)
}

func (*Anything) AnythingDelete(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Anything) AnythingGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Anything) AnythingPatch(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Anything) AnythingPost(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Anything) AnythingPut(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Anything) Delete(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Anything) Get(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Anything) Patch(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Anything) Post(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Anything) Put(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}
