/*
 * httprr.trys.cc
 *
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 inherelab/httprr</code>
 *
 * API version: 0.0.1
 * Contact: in.798@qq.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"github.com/gookit/rux"
	"github.com/inherelab/httprr/app"
)

func BasicAuthUserPasswdGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func BearerGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func DigestAuthQopUserPasswdAlgorithmGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func DigestAuthQopUserPasswdAlgorithmStaleAfterGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func DigestAuthQopUserPasswdGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func HiddenBasicAuthUserPasswdGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}
