/*
 * httprr.trys.cc
 *
 * A simple HTTP Request & Response Service.<br/> <br/> <b>Run locally: </b> <code>$ docker run -p 80:80 inherelab/httprr</code>
 *
 * API version: 0.0.1
 * Contact: in.798@qq.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"github.com/gookit/rux"
	"github.com/inherelab/httprr/app"
)

// Image APIs examples
type Image struct {}

func (grp *Image) AddRoutes(r *rux.Router) {
	r.GET("", grp.Get)
	r.GET("jpeg", grp.JpegGet)
	r.GET("png", grp.PngGet)
	r.GET("svg", grp.SvgGet)
	r.GET("webp", grp.WebpGet)
}

func (*Image) Get(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Image) JpegGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Image) PngGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Image) SvgGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}

func (*Image) WebpGet(c *rux.Context) {
	c.JSON(200, app.BuildReplay(c))
}
